배치 코드 작성.
에러 과정
Caused by: java.lang.NoClassDefFoundError: org/hibernate/boot/model/naming/CamelCaseToUnderscoresNamingStrategy
-> hibernate 의존성 추가하여 해결

driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, jdbc://localhost:3306/db
-> mysql 서버를 키고,
->jdbc:mysql 추가하여 해결

IllegalStateException: Unable to detect database type
-> spring.batch.jdbc.initialize-schema=always
   spring.batch.schema=classpath:org/springframework/batch/core/schema-mysql.sql 추가하여 해결